# Generated by Django 3.2 on 2022-01-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=450)),
                ("last_name", models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "human_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="humans.human",
                    ),
                ),
            ],
            bases=("humans.human",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "human_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="humans.human",
                    ),
                ),
            ],
            bases=("humans.human",),
        ),
        migrations.AddConstraint(
            model_name="human",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="persons name"
            ),
        ),
    ]
