# Generated by Django 3.2 on 2022-01-04 16:30

from django.apps import apps
from django.db import migrations


def add_new_entry(apps, schema_esitor):
    Teacher = apps.get_model("humans", "Teacher")
    Student = apps.get_model("humans", "Student")

    teacher = Teacher.objects.create(first_name="Migration", last_name="Teacher")

    student = Student.objects.create(first_name="Migration", last_name="Student")


class Migration(migrations.Migration):

    dependencies = [
        ("humans", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_new_entry, migrations.RunPython.noop),
    ]
