# Generated by Django 3.2 on 2022-01-04 16:18

import datetime

from django.apps import apps
from django.db import migrations


def add_new_entry(apps, schema_esitor):
    Student = apps.get_model("humans", "Student")
    Teacher = apps.get_model("humans", "Teacher")
    Homework = apps.get_model("homeworks", "Homework")
    HomeworkResult = apps.get_model("homeworks", "HomeworkResult")
    HomeworkDone = apps.get_model("homeworks", "HomeworkDone")

    hw = Homework.objects.create(
        text="Make your own way",
        deadline=datetime.timedelta(days=2),
        created_by=Teacher.objects.get(first_name="Migration", last_name="Teacher"),
    )

    hw_result = HomeworkResult.objects.create(
        student=Student.objects.get(first_name="Migration", last_name="Student"),
        homework=hw,
        solution="my solution",
    )

    hw_done = HomeworkDone.objects.create(homework_done=hw_result)


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0001_initial"),
        ("humans", "0002_auto_20220104_1630"),
    ]

    operations = [
        migrations.RunPython(add_new_entry, migrations.RunPython.noop),
    ]
